//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asc_general.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class like
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> blog_id { get; set; }
        public Nullable<bool> liked { get; set; }
    
        public virtual blog blog { get; set; }
        public virtual user user { get; set; }
    }
}
